---
- name: Pull docker couchdb image and run
  become: true
  community.docker.docker_container:
    image: '{{ docker_image }}'
    name: 'couchdb'
    ports: 
      - "5984:5984"
      - "5986:5986"
      - "4369:4369"
      - "9100-9200:9100-9200"
    env:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
      NODENAME: '{{ ansible_default_ipv4.address }}'
      COUCHDB_SECRET: '{{ cookie }}'
      ERL_FLAGS: '-setcookie \"{{cookie}}" -name \"couchdb@{{ ansible_default_ipv4.address }}\"'
    volumes:
      - ~/couchdb:/opt/couchdb/data