# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: zzyang
instance_flavor: uom.mse.2c9g
instance_network: qh2-uom

# Docker vars
docker_image: couchdb:latest

# Volume
volumes:
  - vol_name: crawler-test-vol
    vol_size: 20
  - vol_name: database-test-vol
    vol_size: 20

# Security group
security_groups:
  - name: database_test_ssh
    description: "Database security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: database_test_http
    description: "Database security group for HTTP"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: database_test_http
    description: "Database security group for HTTP"
    protocol: tcp
    port_range_min: 5986
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0
  - name: database_test_http
    description: "Database security group for HTTP"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: database_test_http
    description: "Database security group for HTTP"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: crawler-test
    volumes: ['crawler-test-vol']
  - name: database-test
    volumes: ['database-test-vol']

