---
# Set up couchdb cluster
- name: Run a script to start couchdb containers
  become: true
  ansible.builtin.script: anotherVer.sh '{{ ansible_default_ipv4.address }}'

  register: results

- ansible.builtin.debug:
    var: results.stdout_lines